# Generated by Django 5.1.3 on 2025-05-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-id']},
        ),
    ]
