# Generated by Django 5.2.1 on 2025-05-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Testimonial/')),
            ],
        ),
    ]
