# Generated by Django 5.2.1 on 2025-05-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField(default='This is default content')),
            ],
        ),
    ]
