# Generated by Django 5.2.1 on 2025-05-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('gmail', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='org_logos/')),
            ],
        ),
    ]
