# Generated by Django 5.2.1 on 2025-05-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_rate', models.FloatField(default=10.0, help_text='Return rate in percentage (e.g., 10 for 10%)')),
            ],
        ),
    ]
