# Generated by Django 5.2.1 on 2025-06-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('total_users', models.PositiveIntegerField()),
                ('projects_completed', models.PositiveIntegerField()),
                ('years_experience', models.PositiveIntegerField()),
                ('team_members', models.PositiveIntegerField()),
                ('agenda_1', models.CharField(max_length=255)),
                ('agenda_2', models.CharField(max_length=255)),
                ('agenda_3', models.CharField(max_length=255)),
                ('agenda_4', models.CharField(max_length=255)),
            ],
        ),
    ]
